# Generated by Django 4.2 on 2024-06-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_category_id_alter_menuitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
    ]
