# Generated by Django 4.2 on 2024-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_ordermodel_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='phone',
            field=models.IntegerField(blank=True, default='0000000000'),
        ),
    ]
